var dictionary_en = {
	'title.addRun' : 'Add a run',
	'title.runs' : 'Runs',
	'title.stats': 'Statistics',
	'title.about' : 'About',
	
	'msg.plvlStart' : 'Paragon level at start',
	'msg.plvlEnd' : 'Paragon level at end',
	'msg.xpStart' : 'XP at start (value / 1000)',
	'msg.xpEnd' : 'XP at end (value / 1000)',
	'msg.duration' : 'Duration (minutes)',
	'msg.author' : 'Author',
	'msg.sources' : 'Source code',
	'msg.recordedRuns' : 'Recorded runs',
	'msg.recordedRunsDuration' : 'Total duration of recorded runs (minutes)',
	'msg.xpGainedWithRuns' : 'XP gained with runs',
	'msg.paragonLevel' : 'Paragon level',
	'msg.xpCurrentLevel' : 'XP in current level',
	'msg.xpRequiredForNextLevel' : 'XP required for the current level',
	'msg.xpMissingForLevelUp' : 'XP missing for level up',
	'msg.completionPercentageCurrentLevel' : '% completion of current level',
	'msg.totalXpAcquired' : 'Total XP acquired',
	'msg.xpAveragePerHour' : 'Average XP / hour',
	
	'msg.xpRequiredToReachNext10' : 'XP required to reach next ten',
	'msg.xpRequiredToReachNext100' : 'XP required to reach next hundred',
	'msg.xpRequiredToReachNext1000' : 'XP required to reach next thousand',
	
	'msg.xpMissingToReachNext10' : 'XP missing to reach next ten',
	'msg.xpMissingToReachNext100' : 'XP missing to reach next hundred',
	'msg.xpMissingToReachNext100' : 'XP missing to reach next thousand',
	
	'msg.completionPercentageNext10' : '% completion of next 10',
	'msg.completionPercentageNext100' : '% completion of next 100',
	'msg.completionPercentageNext1000' : '% completion of next 1000',
	
	'msg.hoursToFarmToReachNext10' : 'Hours to farm to reach next 10',
	'msg.hoursToFarmToReachNext100' : 'Hours to farm to reach next 100',
	'msg.hoursToFarmToReachNext1000' : 'Hours to farm to reach next 1000',
	
	'btn.startPause' : 'Start/Pause',
	'btn.copyTime': 'Copy',
	'btn.reset' : 'Reset',
	'btn.resetAll' : 'Clear everything',
	'btn.save' : 'Save',
	
	'col.duration' : 'Duration',
	'col.lvlStart' : 'Lvl start',
	'col.lvlEnd' : 'Lvl end',
	'col.xpStart' : 'XP start',
	'col.xpEnd' : 'XP end',
	'col.xpTotalStart' : 'XP total start',
	'col.xpTotalEnd' : 'XP total end',
	'col.xpGain' : 'XP gained',
	'col.xpPerHour' : 'XP/hour',
	'col.stat' : 'Stat',
	'col.value' : 'Value'
};